version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_db_container
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    volumes:
      - .:/django-app
    ports:
      - 8000:8000
    image: django01draft_img:1.0
    container_name: django01draft_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  
